import {
  Box,
  Button,
  Flex,
  Heading,
  SimpleGrid,
  Spinner,
  Stack,
  Tag,
  Text,
  useDisclosure,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalCloseButton,
  ModalFooter,
} from '@chakra-ui/react';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { format } from 'date-fns';

import { getAuthorityFlights, getAuthorityGeneralDeclaration } from '../../api/authority';
import { useApiError } from '../../hooks/useApiError';
import type { Document, Flight } from '../../types/domain';

const formatDateTime = (value?: string | null) => {
  if (!value) return '—';
  try {
    return format(new Date(value), 'dd MMM yyyy HH:mm');
  } catch {
    return value;
  }
};

export const AuthorityDashboard = () => {
  const handleError = useApiError();
  const [selectedDocument, setSelectedDocument] = useState<Document | null>(null);
  const disclosure = useDisclosure();

  const { data: flights, isLoading } = useQuery({
    queryKey: ['authority', 'flights'],
    queryFn: getAuthorityFlights,
    onError: (error) => {
      handleError(error, 'Unable to load authority flight feed.');
    },
  });

  const handleViewDocument = async (flight: Flight) => {
    try {
      const document = await getAuthorityGeneralDeclaration(flight.id);
      setSelectedDocument(document);
      disclosure.onOpen();
    } catch (error) {
      handleError(error, 'Failed to retrieve the General Declaration.');
    }
  };

  return (
    <Stack spacing="6">
      <Heading size="lg">Authority Terminal</Heading>
      <Text color="gray.600">
        Access flight manifests and General Declarations generated by operators. All accesses are
        audited for compliance.
      </Text>

      {isLoading ? (
        <Flex align="center" justify="center" h="50vh">
          <Spinner size="xl" />
        </Flex>
      ) : !flights || flights.length === 0 ? (
        <Box
          bg="white"
          borderWidth="1px"
          borderColor="gray.100"
          borderRadius="lg"
          p="10"
          textAlign="center"
        >
          <Heading size="md" mb="2">
            No flights available
          </Heading>
          <Text color="gray.600">
            Once operators submit flights to your jurisdiction they will appear here along with the
            latest documents.
          </Text>
        </Box>
      ) : (
        <SimpleGrid columns={{ base: 1, md: 2 }} spacing="4">
          {flights.map((flight) => (
            <Box
              key={flight.id}
              borderWidth="1px"
              borderColor="gray.100"
              borderRadius="lg"
              bg="white"
              p="5"
            >
              <Stack spacing="3">
                <Flex justify="space-between" align="center">
                  <Heading size="sm">
                    {flight.uid} • {flight.departureAirport?.icaoCode ?? flight.departureAirportId} →{' '}
                    {flight.arrivalAirport?.icaoCode ?? flight.arrivalAirportId}
                  </Heading>
                  <Tag>{flight.status}</Tag>
                </Flex>
                <Text fontSize="sm" color="gray.500">
                  Operator: {flight.operatorName}
                </Text>
                <Text fontSize="sm" color="gray.500">
                  Scheduled departure: {formatDateTime(flight.scheduledDeparture)}
                </Text>
                <Button colorScheme="brand" onClick={() => handleViewDocument(flight)}>
                  View latest General Declaration
                </Button>
              </Stack>
            </Box>
          ))}
        </SimpleGrid>
      )}

      <Modal isOpen={disclosure.isOpen} onClose={disclosure.onClose} size="lg">
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>General Declaration metadata</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            {selectedDocument ? (
              <Stack spacing="3">
                <Text fontWeight="medium">Type: {selectedDocument.type}</Text>
                <Text>Status: {selectedDocument.status}</Text>
                <Text>Storage key: {selectedDocument.storageKey}</Text>
                <Text>Generated at: {formatDateTime(selectedDocument.generatedAt)}</Text>
              </Stack>
            ) : (
              <Text>Loading document details…</Text>
            )}
          </ModalBody>
          <ModalFooter>
            <Button onClick={disclosure.onClose}>Close</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </Stack>
  );
};


